### ISSUE TITLE
Some strings are missing  in the files .pot of PublishPress PRO

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress#1143]
Hi,

I'm checking the language folder for making the translations and some strings are missing  in the files .pot of PublishPress PRO
Please, review or refresh it, because I saw that the legacy translation from free version leaves some strings are still not present in Pro.pot. 
Thanks,
Angelo

**Comment by olatechpro** [comment]
@wocmultimedia 
I'm trying to understand the issue.
1. Pro translation .pot file is outdated?
2. What's the issue with the free version in reference  `I saw that the legacy translation from free version leaves some strings are still not present in Pro.pot.?`
The reason i asked is because free version translation is completely independent on pro

**Comment by olatechpro** [comment]
There's no point in re-adding this issue to milestone every time i remove it without discussion.

1. The language template is already syc
2. The reason this issue is not closed is because i didn't get response on the other issue.
Adding it every time i remove it without discussion is making it difficult for me to have a clean milestone
@stevejburge

**Comment by olatechpro** [comment]
There's no point in re-adding this issue to milestone every time i remove it without discussion.

1. The language template is already syc
2. The reason this issue is not closed is because i didn't get response on the other issue.
Adding it every time i remove it without discussion is making it difficult for me to have a clean milestone.

I can either be closed or stay milestone free till we have further report or response on what to work on
@stevejburge

**Comment by wocmultimedia** [comment]
I have made the translation of PublishPress Pro and sent the updates. The files were ok.
Here's again the translations.
[PRO-PublishPress-ES-FR-IT_TranslationUpdate_November2022.zip](https://github.com/publishpress/PublishPress/files/9952149/PRO-PublishPress-ES-FR-IT_TranslationUpdate_November2022.zip)

Thanks,
Angelo
