### ISSUE TITLE
Save space on Content Overview filters

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#1198]
The new date filters look great but we're running of room.

Should we move all the Metadata filters to the end of the row?

Some suggestions here:

<img width="1443" alt="Screen Shot 2022-11-29 at 1 01 26 PM" src="https://user-images.githubusercontent.com/3868028/204608667-6b8da80b-fec9-494b-93d5-088d9a3402db.png">

**Comment by olatechpro** [comment]
@stevejburge by end of the row, do you mean to the right?

If so, will it matter if there are many filters since it'll eventually occupy all row or you're asking to prevent filters from starting from left, that is, all filters will be restricted to the right side while left area will always be free?

**Comment by stevejburge** [comment]
Thanks @olatechpro 

I guess we should focus on:
- Removing extra spaces where possible
- Making sure extra filters overlap to a second row smoothly

**Comment by olatechpro** [comment]
@stevejburge This is how it look when many filters are enabled:

![filter](https://user-images.githubusercontent.com/46832636/204630949-bc931cd3-303c-4d0d-9b72-bffd564c425b.jpg)

Based on your new response, 
1. You don't want any space between each filter input and/or labels to match Content Overview. **(Understood)**

2. "Making sure extra filters overlap to a second row smoothly", the above screenshot show what happen when filters moved into second row, what adjustment do you want? The space between new line should be reduced or more space added?

3. You still haven't answer my question on moving the Metadata filters to the end of the row and how it should work when filters are much. That is, default filters take the left row and meta filter takes the right row instead of been added to the default filter?

Answering each question with reference to the question number will help understanding better unless any is no longer a requirement.

**Comment by stevejburge** [comment]
1. Thanks
2 and 3. OK, thanks. Yes, maybe we just add the metadata filters after all the default filters?
