### ISSUE TITLE
Add Direct Message support for Slack Notifications

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#335]
Let's add an option for notifications to go directly to a user via Direct Message

**Comment by neddonovan13** [comment]
Thanks for adding Steve! We have a general channel called "notifications" which is for the admins of the site and it collects both PublishPress and Asana notifications, but it would be great if we could personalize the publishpress ones. For now we'll keep using email since that one goes directly to our writers.

**Comment by stevejburge** [comment]
Makes complete sense, thanks @neddonovan13. This is definitely something we should do.

**Comment by andergmartins** [comment]
Hi @neddonovan13 we have a fix for this in the Pro package. Feel free to send us an email to help@publishpress.com and we will be happy to send you an alpha package for testing it.

The notification workflow will use the Slack channel specified in the user's profile. There he can set a custom channel using the `#` char as a prefix, or `@` + the Member ID to send the messages directly to the user in Slack.

Users can copy the member ID following the first part of the tutorial: https://publishpress.com/knowledge-base/slack-mentions-notifications/

Notifications sent to the user who added his Slack member ID to its profile will see the notifications in the Slackbot chat.
