### ISSUE TITLE
Title doesn't change for notifications

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#451]
> I'm using the Notifications feature to send a reminder to the writers on our team 15 days before their post is scheduled to be published. Their content is due to be submitted to us two weeks before publication so the 15 day notice reminds them their blog post is due tomorrow. Per the Publish Press system, I believe I have this set up to ONLY go to people who's posts are still in DRAFT mode. If they've already submitted the post, it would be in Pending Review status and they would not get the reminder e-mail. However, I just had a person who submitted her content early. It is "Pending Review" in Wordpress, but she still got the reminder e-mail and when she did, it was showing the OLD post title that I use when I first set up the Draft blog post and not the actual current post title for the post she wrote which should have been "Birthday Banner Printable Free Download"

**Comment by andergmartins** [comment]
The Reminders plugin is probably scheduling the notification and caching the post data, instead of just the post ID. The notification content is pre-defined when scheduled, and not built dynamically on notification's runtime. It would be better if the notification always have the updated data from the post. 

Should we just store the post ID in the scheduled notification and build the notification's message only when sending the notification?

**Comment by stevejburge** [comment]
@andergmartins Thanks. Yes, that sounds like it would solve the problem

**Comment by andergmartins** [comment]
There is a chance the post's title was updated after the notification was already scheduled. Maybe we should only store the post ID and only parse the content (run shortcodes, etc) when the notification is really being sent?

**Comment by stevejburge** [comment]
@andergmartins Tricky question, right. Yes, perhaps we should do it when the notification is sent
