### ISSUE TITLE
Versions after 1.19.4 prevent new user creation

### ISSUE THREAD

**Issue by the-ferret** [publishpress/PublishPress#456]
Changes made after version 1.19.4 break the new user creation process, as can't generated a new user password.

**Comment by stevejburge** [comment]
@the-ferret Sorry, that's not enough information for a Github bug report. Here's the bug report template ...



Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior




## Current Behavior




## Possible Solution




## Steps to Reproduce (for bugs)



1.
2.
3.
4.

## Context




## Your Environment



* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:
