### ISSUE TITLE
Include the notifications body in Slack messages

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress#636]
This seems like a very sensible request. For example, it allows to @ people:

<img width="564" alt="Screen Shot 2020-06-15 at 11 23 02 AM" src="https://user-images.githubusercontent.com/3868028/84675750-ae723a00-aefa-11ea-93dc-360cf1e5a0c3.png">

**Comment by andergmartins** [comment]
Just a note: For mentioning users we have to use the user's ID on Slack, instead of his name:

https://help.workast.com/hc/en-us/articles/360027461274-How-to-find-a-Slack-user-ID

**Comment by andergmartins** [comment]
Changed the themes a little. The "Full" theme now uses the notification body instead of a pre-defined text.
The "Clean" theme uses the current pre-defined short message text:

<img width="803" alt="Screen Shot 2020-10-16 at 17 20 50" src="https://user-images.githubusercontent.com/407131/96305313-15504e80-0fd4-11eb-9e8b-081253d31170.png">

I will need to update those images later.
