### ISSUE TITLE
PublishPress 3.0.0 breaks my instance

### ISSUE THREAD

**Issue by jorr** [publishpress/PublishPress#740]
Hi guys,

I wrongly posted this in the release issue, apologies about that.
Updating to PP 3.0 has broken my site with a fatal error on the backend. I checked the PHP version and it seems to be good (if this is a PHP-version related error at all, which I am not sure about).

Hard to debug what's going on on my side but maybe you would have ideas.
Very superficially, it seems like the problem is in the Reminders/Core combo, is it maybe a question of having an outdated version or Reiminders? Mine is 1.2 and the plugins panel doesn't offer me anything newer.

This is the stack trace in the log:

[17-Nov-2020 10:15:01 UTC] PHP Fatal error: Uncaught exception 'Exception' with message 'Service "workflow_controller" not found in the container' in [..]/wp-content/plugins/publishpress/libraries/Notifications/Traits/Dependency_Injector.php:39
Stack trace:
#0 [..]/wp-content/plugins/publishpress-reminders/modules/reminders/reminders.php(176): publishpress->get_service('workflow_contro...')
#1 [internal function]: PP_Reminders->checkBeforePublishingCronJob('')
#2 [..]/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)
#3 [..]/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 [..]/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 [..]/wp-content/plugins/publishpress/modules/improved-notifications/improved-notifications.php(244): do_action('publishpress_wo...')
#6 [internal function]: PP_Improved_Notifications->action_aft in [..]/wp-content/plugins/publishpress/libraries/Notifications/Traits/Dependency_Injector.php on line 39

**Comment by andergmartins** [comment]
Hi @jorr,

No problem, thank you for reporting the issue.
Sorry about that, but this is happening because PublishPress Reminders is a deprecated add-on and is not compatible with the last major release. 

Its code, and the other add-ons, were merged into PublishPress Pro v2.0, so you can deactivate and delete them from your site. We added a note on this blog post when we released it: https://publishpress.com/blog/publishpress-pro/

After removing the legacy PublishPress add-ons you would be able to install PublishPress Pro v3 again.

Feel free to report any other issue you see. We are glad to help.

Thanks
